SELECT ugu.USER_ID, ugu.NICKNAME, SUM(ugb.PRICE) as TOTAL_SALES FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY ugb.WRITER_ID HAVING SUM(ugb.PRICE) >=700000
ORDER BY SUM(ugb.PRICE)